# -*- coding: utf-8 -*-
"""Stats.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H9ziGSvfpzRbGbxCMIRV07hcqt1VKXsz
"""

import numpy as np
from scipy import stats

# Sample data arrays
employee = np.array([5, 5, 5, 5, 6, 6, 7, 8, 8, 8, 9, 11, 12, 12, 13, 13, 17, 19, 19, 21])
investment = np.array([3146, 3152, 3307, 3466, 3933, 4074, 4190, 4945, 5456, 6743, 6850, 7101, 7343, 8844, 9095, 9200, 9315, 9508, 9521, 9521])
expenses = np.array([21770, 25270, 27316, 27867, 28339, 29232, 30989, 37339, 37931, 39172, 42661, 43348, 43883, 43924, 44127, 44986, 45001, 45237, 46931, 46931])
sales = np.array([146233, 148991, 157278, 209618, 218211, 237164, 239073, 273295, 275179, 289909, 305607, 311500, 341853, 351158, 383053, 388936, 450807, 470227, 476594, 476594])

# Function to calculate statistical measures
def calculate_statistics(data):
    mean = np.mean(data)
    median = np.median(data)
    mode = stats.mode(data)
    skewness = stats.skew(data)
    kurtosis = stats.kurtosis(data)
    return mean, median, mode, skewness, kurtosis

# Calculating statistics for each dataset
employee_stats = calculate_statistics(employee)
investment_stats = calculate_statistics(investment)
expenses_stats = calculate_statistics(expenses)
sales_stats = calculate_statistics(sales)

# Printing the results
print("Employee Stats: ", employee_stats)
print("Investment Stats: ", investment_stats)
print("Expenses Stats: ", expenses_stats)
print("Sales Stats: ", sales_stats)

